### PR TITLE
Bump to 0.2.0

### PR DESCRIPTION
**Pull request by kenodegard**
Changelog: https://github.com/conda/conda-content-trust/releases/tag/0.2.0
Xref: https://github.com/conda/conda-content-trust/issues/84

### CODE REVIEW

**Review by marcoesters — COMMENTED** [review]
This needs a `skip: true  # [py<38]`: https://github.com/conda/conda-content-trust/blob/0.2.0/pyproject.toml#L28

We also add `--no-build-isolation` as a standard pip flag.

`wheel` is should not be necessary for `hatchling` builds (the linter will complain, but that will be fixed in the next release)

**Review by marcoesters — APPROVED** [review]
Would be interesting to decide whether the optional dependency is worth adding later to get the tests to work. Or why the tests fail even though the upstream code should have accounted for it.

**Review by Jrice1317 — APPROVED** [review]
LGTM

**Comment by kenodegard** [comment]
> Would be interesting to decide whether the optional dependency is worth adding later to get the tests to work. Or why the tests fail even though the upstream code should have accounted for it.

agreed, we will need to investigate if the feature is needed and if it is we absolutely need to get `securesystemslib` onto defaults

the tests pass upstream bc we depend on `conda-forge::securesystemslib`

FYI we also disabled the tests on conda-forge, the tests failed there too even with the package because the build env didn't include any GPG keys

**Review by skupr-anaconda — APPROVED** [review]
LGTM

**Pull request merged**
